### ISSUE TITLE
Feature Request: Nop a whole function

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/cutter#2555]
I'd be nice to be able to **replace all assembly instructions related to a function (or a block in gaph view) with `nops`.**

**Refs**
Somewhat related to https://github.com/rizinorg/cutter/issues/2147

**Comment by xarkes** [comment]
Random thought about this issue which might go a bit off-topic:
I'm not sure we want to provide the GUI with every possible action a user would have to do in their reverse engineering tasks (IMHO to `nop` a whole function is quite rare or doesn't fit for every use case, I could be wrong though). So my opinion is we should close this issue.

However, I think that when we'll have a decent python API what could be considered is to provide the users with common python scripts that might be useful in any reverse engineering task. I imagine a list with all kind of scripts and the user would have to look for "nop a function" or "replace instructions", select the script, read briefly its description and its source code, and simply execute it. It's rather common to live with a full set of python scripts alongside a reverse engineering framework because it does not always do what one wants. I think that centralizing all these scripts could be great to share it among reversers and improve the UX overall.

**Comment by ITAYC0HEN** [comment]
Love the latter idea :)
Regarding this specific option of NOPing a function, I think it won't be implemented as "Nop a function", but rather Cutter will support multiline actions. So select multiple lines ( a function, a block, two instructions) and Right Click -> Edit -> Nop instructions

**Comment by karliss** [comment]
@ITAYC0HEN Does it even make sense to replace all function instructions with NOP? That would likely just crash once CPU reaches the next instruction after the NOPs. If the intention is to have function have no effect then wouldn't the simplest thing be inserting ret at the start of function? It would still not work if function is supposed to return a some nontrivial type but neither would noping or almost anything automatic.

**Comment by ITAYC0HEN** [comment]
I am not the one to judge. There is no reason not to provide a generic interface for executing actions on several instructions . There are many reasons to do so and it's up for the user how they want to use it. I don't think providing a "nop a function" functionality is good. But running an action (nop) on multiline selection is fine and trivial. 

I personally don't remember myself NOPing an entire function but sure did NOP dozens of instructions

**Comment by Semnodime** [comment]
Unfortunately, I didn't know about Cutter's plugin capability, when I opened this issue

Providing multiline support (#2601) along a nice python api (as imagined by @xarkes) does not fully solve the given issue, but I agree that this woud be the most favorable solution considering the diverse set of user requirements.

----

In the meantime,
I copy-pasted together some quick'n'dirty plugin that allows me to nop a whole basic block or even a whole function.
![image](https://user-images.githubusercontent.com/19511852/146636766-ff74d857-38ac-43a6-aaa8-2149c40a85b6.png)

----
P.S.
@karliss yes, nopping a function would crash the cpu, ...unless, the function is not used anyway. I am currently cleaning a binary from all unrelated code as this allows me to focus better on the actual control flow and set of executed instructions.
Also, I patched and partially re-wrote the CutteDRcov plugin by @oddcoder to easily see which functions are obsolete. (PR will be posted, when the code has been polished even further)
