### ISSUE TITLE
Windows Building docs: Mention where to download Qt and Cmake, and their versions

### ISSUE THREAD

**Issue by ITAYC0HEN** [rizinorg/cutter#2560]
**Is your feature request related to a problem? Please describe.**

The [building instructions for Windows](https://cutter.re/docs/building.html#building-on-windows) is lacking information as where to download cmake (easy) and where to download Qt (little bit more complicated). In addition, it doesn't specify the recommended version to install and the supported versions.

**Describe the solution you'd like**

Enhance this part in the documentation, add these pieces of information and make sure that someone who have never heard of "qt" and "cmake" will be able to go through the building process successfully.

**Comment by karliss** [comment]
I have few concerns.

Who the target audience for these instructions? What are the expectations for their skills and willingness to learn? Why do the they want to build cutter themselves instead of using prebuilt release or dev-build from CI. What are the expectations for specific platform users. 

If someone is in hurry doesn't know anything and is unwilling to learn, is there point in compiling Cutter themselves? What will they gain by doing it themselves? If they want the very latest dev build they should download that, and if necessary we should make it more easily accessible. The basic build that they can do by strictly following build instructions won't have all the features enabled like release package do and it potentially won't be fully packaged for convenient moving around as some things require more complicated process and basic understanding of what you are doing.

My assumption for windows is that go the website and download the things is default way of obtaining software on Windows unless specified otherwise.

More details on various options for setting up dev environment are described in development environment setup page. I don't think all of that belongs in building instruction page. Maybe we should add link to it in building page. I would expect anyone who is seriously thinking of participating in development to read it as well. Basic build from command line  isn't really the way for doing development unless you call emacs your operating system in which case you can probably figure out things yourself or get by skimming the docs.

For Qt there are ~3 options 2 of which are described in dev setup page. None of the options are great.
* The obvious way of downloading from Qt website - this requires qt account. And there is also a bunch of junk. I don't want to force people doing this.
* vcpkg - no registration, no additional setup if you are using Visual Studio, takes a some time to compile.
* cutter-deps - simple and small download, doesn't include debug version

**Comment by karliss** [comment]
More importantly there is nothing mentioned about meson and ninja which are required for rizin.

**Comment by karliss** [comment]
Even though I sounded very negative above, I don't mind turning some of the names into links.

**Comment by ITAYC0HEN** [comment]
might have been fixed in #2590

**Comment by Surendrajat** [comment]
@ITAYC0HEN I can see all the tools with links to download page, so yeah let's close this one.
