### ISSUE TITLE
Select all lines within a fuction

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/cutter#2593]
**Is your feature request related to a problem? Please describe.**
According to @ITAYC0HEN (s. issue #2555) "nop whole function" will likely be solved by allowing to nop multiple lines at once (as wished for in #2147).

The process of selecting multiple lines plays a major role in time efficiency when applying multiline operations repeatedly__ 

**Describe the solution you'd like**
UI option to select all lines within a function, eg. by right click.

**Comment by ITAYC0HEN** [comment]
Hi, thanks for the idea! I don't think we will provide a `right-click > select all lines in a function.`. Users will have to do it by themselves with their mouse.
Some alternatives we will consider will be to click on offset X to start the selection, and then click on offset `X+Y` to end selection and it will select the entire range. Also, something like `Right click -> Select range` with multiple predefined options as well as custom range.

All this can not be done using our current disassembly widget.

Since this issue is too specific now, and from my experience, it'll probably be stuck in the backlog forever, I think I will close it and we will open a new one when the required base-functionality will be in place.
