### ISSUE TITLE
Cutter freezes upon entering invalid instruction

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/cutter#2629]
**Environment information**
* Operating System: linuxmint 20.1
* Cutter version: 1.12.0
* File format: any
 * Arch: N/A
 * Type: N/A

**Describe the bug**
Cutter turns unresponsive.

**To Reproduce**
1. Load shellcode `5390909090` without analysis.
2. Disassembly > Select Line 0x0001 > <kbd>right click</kbd> > Edit... > Instruction > `lea eax, [s]`
3. Type the `t` after `s` like attempting to write `lea eax, [str]`
4. Observe non-responding application

**Expected behavior**
Cutter remaning responsive.

**Screenshots**
![image](https://user-images.githubusercontent.com/19511852/110458399-0033a380-80cc-11eb-835d-b9f8e54b0189.png)

**Comment by karliss** [comment]
Was able to repeat using 1.12 appimage from release page. Could not repeat using local build of latest master.

**Comment by karliss** [comment]
As for the actual mechanism of hanging it's a combination of two issues:
* r2/rizin assembler printing infinite amount of `Expected register number 'st'` to stderr
* deadlock in Cutter output redirection code when large amount of text gets printed to stderr the existing issue for that is #2070 

The first issue can be observed by running Cutter from terminal with "--no-output-redirect" flag. I assume that is fixed since latest dev build of Cutter compiled against rizin doesn't flood the terminal with `Expected register number 'st'`

**Comment by karliss** [comment]
Also thank you for the precise and minimized bug reproduction steps. It really helps investigating such issues.

**Comment by karliss** [comment]
A new version of Cutter with rizin has been released in which the first part of of issue has been solved. Couldn't repeat the problem using it just like it couldn't be repeated using lasted build from master at the time of previous comment.
