### ISSUE TITLE
Unexpected CMD launched with Cutter with no way of hiding or closing

### ISSUE THREAD

**Issue by Ceus** [rizinorg/cutter#2657]
**Environment information**
* Operating System: Windows 10
* Cutter version: 2.0.0
* File format: PE
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
Using the Cutter.exe binary to launch the program also launches a Command Prompt immediately with the File Selection dialog. I am not sure if this was the intention, as I do not see it in the release notes or images (unless I am missing it).

**To Reproduce**
1. Launch Cutter using Cutter.exe

**Expected behavior**
Launching Cutter using the Cutter.exe binary will launch the application with the Select File dialog without a Command Prompt window or have the Command Prompt window hidden or close after file is selected.

**Screenshots**
![ShareX-04-02-21_560](https://user-images.githubusercontent.com/3145889/113461962-66b69380-93e4-11eb-86f1-518e6ff58f20.png)
![ShareX-04-02-21_563](https://user-images.githubusercontent.com/3145889/113461963-66b69380-93e4-11eb-8620-724f2c59c55f.png)

**Additional context**
This is based on the previous release version 1.12.0

**Comment by karliss** [comment]
The terminal windows is there so that stdout ouptut from cutter plugins, rizin, python plugins, and other parts can be redirected to the console widget. If anyone has a suggestions for way of configuring the redirection that works without the terminal window help would be appreciated.

The actual opening is controlled by executable flag marking if the executable is GUI or terminall program, it is set by CMake.
When testing this keep in mind that some messages to console widget are printed directly so just because you see somthing doesn't mean everything is redirected correctly.

**Comment by Ceus** [comment]
> The terminal windows is there so that stdout ouptut from cutter plugins, rizin, python plugins, and other parts can be redirected to the console widget. If anyone has a suggestions for way of configuring the redirection that works without the terminal window help would be appreciated.
> 
> The actual opening is controlled by executable flag marking if the executable is GUI or terminall program, it is set by CMake.
> When testing this keep in mind that some messages to console widget are printed directly so just because you see somthing doesn't mean everything is redirected correctly.

Would it be possible to have this window listen for new information and relay that information to the console window or convert that window to a widget? Either way, I don't mind taking a look at this. I'll update if I find/think of something.
