### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by ddkwork** [rizinorg/cutter#2701]
**Environment information**
* Operating System:manjaro on termux
* Cutter version:latest
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

Hello i used clion for build cutter on termux manjaro arm64,but not work for me.
![Screenshot_20210605_100910_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/120876907-25aa4d80-c5e6-11eb-86d0-2ac5dc4dd7ac.jpg)

Another problem is how to load symbol, i  find the api name do not show.

**Comment by xarkes** [comment]
Hello,
We do not officially support Termux, so it would be really helpful if you could start by filling the issue template properly i.e. giving the exact steps on how you tried to build Cutter (what cmake options are enabled?) and share the log file that is mentioned in the error window.
Thanks :)

**Comment by visagemsc** [comment]
@ddkwork How did you compile or otherwise get the optional dependencies, if you ever did those? I'm trying to build Cutter but I can't build the syntax highlightibg library without `kdesrc-build` not recognizing Termux (following [KDE's own instructions for building Kate](https://kate-editor.org/build-it/)).
