### ISSUE TITLE
Feature Request: Hexdump select range within entropy or with known format

### ISSUE THREAD

**Issue by Andersama** [rizinorg/cutter#2820]
**Is your feature request related to a problem? Please describe.**

The existing select range options are manually input as a start address or end address pair. Recently I found an interesting section of memory which was clearly json formatted, but given how large it was it wasn't particularly nice to scroll to both ends. It crossed my mind that it might be a nice feature to be able to select a section of memory if it's immediately obvious that it's a particular format. In similar fashion given there's entropy analysis another solution / approach would be options to select ranges of memory given some known entropy.

**Describe the solution you'd like**

A new select range option / options for fairly well known / common formats. It may be far more convenient / handy to have an option for selecting or shortcut to jump to parts of the hexdump where there's a significant change in entropy. Potentially something like pagedown or pageup shortcuts but specifically to jump to sudden entropy changes or shortcuts to navigate the formatted bit of memory.

**Describe alternatives you've considered**

I'm not familiar enough with rizin or cutter to know if this might have an obvious solution. This very well could be something that could be accomplished with a script. This could also be it's own plugin.

**Additional context**

**Comment by ITAYC0HEN** [comment]
Hey Andersama! Thank you for your suggestion. While we try to keep Cutter very flexible and rich in features, I think that this feature request is too specific, since selecting something based on arbitrary entropy is prone to errors. Instead, we have several mechanisms that could help you in such cases straight from the Console widget.

For example, you could put your cursor at the beginning of the JSON strings, and use the `psz` (Print String Zero-terminator) command to print a null-terminated string from this location. Then, it is just a matter of copying the output from the Console widget.

Here is how it looks like for /bin/ls XML string:

![image](https://user-images.githubusercontent.com/20182642/141678153-13bf5d3b-d296-4a6c-b494-9d71636bdea3.png)

I will close this issue for now. Let us know what you think and we would be happy to open this feature request in a case that something is changed. ❤️

**Comment by Andersama** [comment]
No problem, and thanks for example, I think when I tried selecting the full range in the hex dump cutter crashed, maybe this'll work instead.

**Comment by Andersama** [comment]
Perhaps the issue should be for an integration of a quicker way to do printing commands? Seems like pj and psz both would be useful, (and I'm sure other printing commands also would be as well) but the command line version only processing the "block" size would seem to suggest it should be called over and over to append to a potential buffer? Seems like this could be added into cutter.

Second thought I had because I'm not entirely clear, is there a way to do an untruncated version of psz / pj in commandline? EG: is there a command to get the string's size and then set the block size?
