### ISSUE TITLE
symbol lookup error: cutter: undefined symbol

### ISSUE THREAD

**Issue by xade93** [rizinorg/cutter#2909]
**Environment information**
* Operating System: Arch Linux
* Cutter version: 2.0.4-1
* Obtained from:
  - [ ] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [x] Distribution repository

**Describe the bug**
Upon running cutter, it crashes and report "cutter: symbol lookup error: cutter: undefined symbol: _ZN6PySide16fillQtPropertiesEP7_objectPK11QMetaObjectS1_PPKcj"

**To Reproduce**
1. install rz-cutter from any source on arch (I tried `community/rz-cutter` and `blackarch/rz-cutter`)
2. run it

**Screenshots**
![image](https://user-images.githubusercontent.com/24752033/159170332-6cf33277-8ec6-4e54-bfeb-30fa05caf843.png)

**Comment by notxenonbox** [comment]
Hello! I had the same issue as you did. The package in the arch repos is out of date and built against older so files. Building from source fixes the issue.

The only problem is that the build will fail, because for some reason include paths are wrong.

So you gotta download the PKGBUILD from the ABS, [see the wiki](https://wiki.archlinux.org/title/Arch_Build_System#Retrieve_PKGBUILD_source) and you need to apply this patch to it.

```patch
--- a/repos/community-x86_64/PKGBUILD
+++ b/repos/community-x86_64/PKGBUILD
@@ -34,7 +34,7 @@ prepare() {

 build() {
   cd cutter
-  cmake -B build \
+  CXXFLAGS=-I/usr/include/KF5 cmake -B build \
     -DCMAKE_INSTALL_PREFIX=/usr \
     -DCMAKE_BUILD_TYPE=None \
     -DCUTTER_ENABLE_PYTHON=ON \
```

The `aur/rz-cutter-git` has the same issue, there even the source URLs are messed up.

**Comment by kallisti5** [comment]
Just ran into the same issue.  I has riscv64 stuff to debug :scream:

**Comment by karliss** [comment]
I was able to install and run it yesterday. Problem solved?

**Comment by karliss** [comment]
I assume it got fixed by one of the rebuilds which happened after this issue was created either https://github.com/archlinux/svntogit-community/commit/20d8eaa05c6f79172b537627ebd4c5eb38de911a or  https://github.com/archlinux/svntogit-community/commit/364ba192ef48f37be70684002f9cabc95ba03406 .

If the problem reappears please create a new issue.
