### ISSUE TITLE
RizinCpp.h:110:34: warning: 'iterator<std::input_iterator_tag, char *>' is deprecated

### ISSUE THREAD

**Issue by XVilka** [rizinorg/cutter#3033]
**Environment information**
* Operating System: Mac OS 12.5.1 on ARM64
* Cutter version: https://github.com/rizinorg/cutter/commit/e6db27135dcb9f2aa46bde91ac5c82e64ed51df3
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: -

**Describe the bug**

```
/Users/user/rizin/cutter/src/core/RizinCpp.h:110:34: warning: 'iterator<std::input_iterator_tag, char *>' is deprecated [-Wdeprecated-declarations]
    class iterator : public std::iterator<std::input_iterator_tag, T *>
                                 ^
/Users/user/rizin/cutter/src/widgets/Dashboard.cpp:141:30: note: in instantiation of member class 'CutterRzList<char>::iterator' requested here
        for (const auto &lib : CutterRzList<char>(libs)) {
                             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__iterator/iterator.h:27:29: note: 'iterator<std::input_iterator_tag, char *>' has been explicitly marked deprecated here
struct _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 iterator
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__config:1066:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
#  define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__config:1043:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
1 warning generated.
```

**Comment by p371jah** [comment]
`std::iterator` is deprecated in C++17, but we use C++11.
https://github.com/rizinorg/cutter/blob/dev/CMakeLists.txt#L46

**Comment by karliss** [comment]
I was initially thinking that clang was getting silly and warning about stuff which should only be deprecated in >=C++17 even though project is targeting  C++11 version, but it turned out that using QT6 forces all the project files compiled in C++17 mode. 

I previously thought C++17 was only requirement for compiling the newer versions of Qt6 itself while still allowing the users of Qt to library target older C++ versions. But I guess that might not be the case. Might need to be investigated to confirm whether this really is the case or it's just bad default behavior for Qt cmake files.

This doesn't mean Cutter can't  be written in way that's compatible with QT6 + C++17 while still targeting older versions of C++ and QT5 compatiblity . I would really like to keep the possibility of building on non bleeding Linux distros using the available compiler and system libs. Both to make things easier distro packagers and reducing the chance that they will ship old outdated Cutter and also to make it easier for people using such distros contributing to Cutter. 

Especially in combination with github actions dropping older Ubuntu images (still supported by Ubuntu) raises the need to setup CI builds which run in a docker container based on minimum target we want to support. As minimum supported version only works if there CI jobs regularly testing that it still works.

**Comment by XVilka** [comment]
I am all for keeping backward compatibility as long as it doesn't create too much headache for us. If it's possible to address most of these warnings *without* the need to tie ourselves to the high C++ or Qt version - that should be done. On the other hand, in these tricky cases we could just have `#ifdef`s, probably.

**Comment by turlututututu** [comment]
Hi guys, is anyone working on this? I'am looking for a nice issuer for a newcomer!

**Comment by karliss** [comment]
I don't think anyone is currently is working on this.  Feel free to make a pull request. This should be easy to fix.
