### ISSUE TITLE
`cmake -B build -DCUTTER_ENABLE_PYTHON=ON -DCUTTER_ENABLE_PYTHON_BINDINGS=ON` error

### ISSUE THREAD

**Issue by jaf0rk** [rizinorg/cutter#3041]
I need to python  bindings, but an error is reported: `By not providing "FindShiboken2. cmake" in CMAKE_ MODULE_ PATH this project
has asked CMake to find a package configuration file provided by
"Shiboken2", but CMake did not find one.`
OS: Win_64
![image](https://user-images.githubusercontent.com/48431086/190317599-094db9d5-e382-4cd5-b181-12169f05d816.png)

**Comment by karliss** [comment]
How did you obtain shiboken2/pyside ? If you don't remember getting it then most likely don't have it.  Last time I looked at it, most prebuilt qt packages didn't have it included, so it's a bit tricky unless you are on a Linux distro which has it in standard repositories. 

Your options are pretty much:
* compile qt + shibobken yourself
* download the version of QT+shiboken that Cutter CI uses for official release builds. You can get it from https://github.com/rizinorg/cutter-deps .

Why do you want to compile Cutter with python yourself? Depending on what you want to do you might not need it.
* If all you want is latest dev build instead of last release you can download the build for every commit from here https://github.com/rizinorg/cutter/actions/workflows/ci.yml  They have the python support and most important plugins like rz-ghidra included.
* If you just want getting started with Cutter development and contributing to it, you can just build cutter without python support. Unless you are directly working on python extension interface, most Cutter development work doesn't require it.

**Comment by XVilka** [comment]
Closing since there is no response and reproducing it impossible without more information. Feel free to open a new issue if you come with additional information.
