### ISSUE TITLE
CMake >=2.27 - migrate from `FindPythonInterp` and `FindPythonLibs` to `FindPython`

### ISSUE THREAD

**Issue by XVilka** [rizinorg/cutter#3211]
These modules have been deprecated since CMake 3.12

```
CMake Warning (dev) at CMakeLists.txt:96 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /opt/homebrew/bin/python3.11 (found version "3.11.4")
CMake Warning (dev) at CMakeLists.txt:97 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonLibs: /opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib/libpython3.11.dylib (found suitable version "3.11.4", minimum required is "3.5")
CMake Warning at CMakeLists.txt:157 (message):
  KSyntaxHighlighting has been disabled because not supported in QT6
```
https://cmake.org/cmake/help/latest/policy/CMP0148.html

https://repology.org/project/cmake/versions

Currently the complete migration stopped by Ubuntu 18.04 - it has CMake [3.10.2](https://launchpad.net/ubuntu/+source/cmake). Bionic reached EOL already though, but still on extended support: https://endoflife.date/ubuntu

See also https://github.com/rizinorg/cutter/issues/2509

**Comment by r3yc0n1c** [comment]
Hi, I'd like to work on this!

**Comment by karliss** [comment]
Please don't do this right now.

**Comment by karliss** [comment]
The changes will be include as part of https://github.com/rizinorg/cutter-deps/issues/15 . Cmake <3.12 will be kept by cmake version check, the amount of conditional logic wasn't too bad.

Overall the new modules are easier to use and configure and make the CI config simpler since they require only specifying `-DPython[3]_ROOT_DIR` in comparison with old one which required PYTHON_LIBRARY PYTHON_INCLUDE_DIR PYTHON_EXECUTABLE. Not only that's 3 times less paths, you don't need to be as concerned with platform specific file paths within the root. It's also the mechanism pyside cmake files use for looking up python.
