### ISSUE TITLE
Editing Global Variable Displays Incorrect Variable in Dialog 

### ISSUE THREAD

**Issue by Zack08110** [rizinorg/cutter#3340]
**Environment information**
* Operating System: WSL - Ubuntu22.04, Host OS - Windows 10 19045.4355 Build
* Cutter version: 2.4.0-dev-7664367 and release version 2.3.4
* Obtained from:
  - [x] Built from source - commit 76643671fd1a5384640e492d200d36f78b9db25f
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: ELF 64-bit - The debug build of the cutter binary itself

**Describe the bug**

When trying to edit the Global variable the **Dialog** shows a variable **different** from the variable which was **clicked** upon.

**To Reproduce**

1. Go to the Globals tab for the binary
2. Right-click on any of the shown Global Variables
3. Click on `Edit Global Variable`
5. See the difference between the address of the Global Variable and the Variable Shown

**Expected Behaviour**

The Dialog should show the variable which was clicked upon 

**Screenshots**

![image](https://github.com/rizinorg/cutter/assets/54111579/6c70264f-49b9-45c0-82b5-2f237193028c)

**Additional context**

I am new to this codebase and would like to explore and research this issue if it is an issue and resolve it.

**Comment by Zack08110** [comment]
The `globals` variable of type `QList<GlobalDescription> GlobalsWidget::globals` is storing the data in a different order than what is shown in the globals tab

**Comment by Zack08110** [comment]
The current solution coming to my mind is to sort the Globals QList based on the type of sorting is selected by the user every time

**Comment by karliss** [comment]
> The current solution coming to my mind is to sort the Globals QList based on the type of sorting is selected by the user every time

Nothing of the sort should be necessary. All the the other similar widgets are working fine without doing something like that.

Most likely there is mixup of index for globalsModel (responsible for querying and storing retreived data from rizin) and globalsProxyModel (the one responsible for filtering and sorting). The fix should be to query data from proxyModel, since that's what the tableview is interacting with and thus that's what the current selection index is for.
