### ISSUE TITLE
Build failure against PySide >= 6.8

### ISSUE THREAD

**Issue by misaka18931** [rizinorg/cutter#3384]
**Environment information**
* Operating System: NixOS
* Cutter version: 
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

`PySide::SignalManager::instance()` was removed [here](https://code.qt.io/cgit/pyside/pyside-setup.git/diff/sources/pyside6/libpyside/signalmanager.h?id=33bd61d13d8d9e3794b6049891be62f3351313d9) in [this commit](https://code.qt.io/cgit/pyside/pyside-setup.git/commit/sources/pyside6?id=33bd61d13d8d9e3794b6049891be62f3351313d9), before the release of 6.8.0.

This change in pyside caused a compilation error on `cutter/src/common/PythonManager.cpp:136:28` which called `PySide::SignalManager::instance().clear();`:

```
/build/source/src/common/PythonManager.cpp:136:28: error: 'instance' is not a member of 'PySide::SignalManager'
  136 |     PySide::SignalManager::instance().clear();
```

Inferring from code in that same commit, it seems that this line is no longer needed.
But I'm not sure as I'm not familiar with Qt.

**To Reproduce**

Build cutter against Qt & PySide >= 6.8

**Expected behavior**

No build failure.

**Additional context**

The full compilation log can be viewed on the build server of NixOS. [link](https://hydra.nixos.org/build/274852839/nixlog/1)

**Comment by freerig** [comment]
Same issue,
Also, it seems like nix didn't cached it...
Did you find out ?
Thx

**Comment by karliss** [comment]
See the  [Arch Linux patch](https://gitlab.archlinux.org/archlinux/packaging/packages/rz-cutter/-/blob/main/pyside-6.8.patch?ref_type=heads) as temporary solution  if you really need to compile it using Qt & PySide >= 6.8 right now.

Proper fix within Cutter will need to be little bit more complicated, but in distro specific build scripts where you know that you will be using at least that version it's probably fine.

By the way wasn't the hole point of nix that each software can have it's own version dependencies so that you aren't forced to use latest versions of everything?

**Comment by misaka18931** [comment]
> Same issue, Also, it seems like nix didn't cached it... Did you find out ? Thx

@freerig 
I would recommend using the package in nixos-24.05, until when cutter fixed it properly.

> By the way wasn't the hole point of nix that each software can have it's own version dependencies so that you aren't forced to use latest versions of everything?

Thanks for the workaround. 
That's kinda true. The build failure is happening only on the unstable channel where everything is built against the latest versions and things are expected to break.
I thought that simply removing that line would do the trick, raised the issue just to confirm, but it seems that's not the case.
